version: "3.9"


services:

  outil_test:
    image: outil_test:latest
    # Necessary for accessing and creating files with the current user
    user: "${USER_ID:-root}:${GROUP_ID:-root}"
    ports:
      - "8000:8000"
    volumes:
      - ..:/usr/src/databases-timeseries-analysis
      - ~/.bash_history:/root/.bash_history
    depends_on:
      - postgres
      - questdb
      - timescale
      - influxdb
    #    env_file:
#      - ../config/dev.env
    restart: unless-stopped

  timescale:
    image: timescale/timescaledb-ha:pg14.9-ts2.11.1
    command: |
      postgres -c log_connections=on -c max_locks_per_transaction=2000 -c client_min_messages=debug5 -c log_min_messages=ERROR
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: 'password'
      POSTGRES_USER: 'test'
    restart: unless-stopped


  postgres:
    image: postgres:14.8-alpine
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: 'password'
      POSTGRES_USER: 'test'
    restart: unless-stopped

  questdb:
    image: questdb/questdb:7.3.1
    environment:
      QDB_PG_RECV_BUFFER_SIZE: 900M
    expose:
      - "9000"
      - "8812"
      - "9009"
    restart: unless-stopped


  mongo:
    image: mongo:7.0.1
    restart: always
    environment:
      MONGO_INITDB_USERNAME: test
      MONGO_INITDB_PASSWORD: password
      MONGO_INITDB_DATABASE: mongo
    expose:
      - "27017"


  influxdb:
    image: influxdb:2.7.1
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: test
      DOCKER_INFLUXDB_INIT_PASSWORD: password
      DOCKER_INFLUXDB_INIT_ORG: holmium
      DOCKER_INFLUXDB_INIT_BUCKET: test
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: token
      INFLUXDB_TOKEN: tokentest
      INFLUX_HOST: influxdb
    expose:
      - "8086"
    ports:
      - "8086:8086"
    restart: unless-stopped




