version: "3.9"

services:

  outil_test:
    image: outil_test:latest
    build:
      context: ../
      args:
        python_version: ${PYTHON_VERSION:-3.11.4-slim}
      dockerfile: docker/dockerfile
      cache_from:
        - outil_test:latest