version: "3.9"

services:

  outil_test:
    image: database-timeseries-analysis:latest
    build:
      context: ../
      args:
        python_version: ${PYTHON_VERSION:-3.11.4-slim}
      dockerfile: docker/dockerfile
      cache_from:
        - database-timeseries-analysis:latest